### ISSUE TITLE
Does not work if image size downloaded is above 3072kb

### ISSUE THREAD

**Issue by Venefilyn** [EliteDangerous-Subreddit/reddit-twitter-bot#6]
Stacktrace:

```
Traceback (most recent call last):
  File "reddit-tweeter.py", line 207, in <module>
    main()
  File "reddit-tweeter.py", line 168, in main
    tweeter_func(twitter_api, post)
  File "reddit-tweeter.py", line 104, in tweeter_func
    twitter_api.update_with_media(filename=img_path, status=post_text)
  File "/home/spytec/reddit-twitter-bot/venv/lib/python3.7/site-packages/tweepy/api.py", line 220, in update_with_media
    headers, post_data = API._pack_image(filename, 3072, form_field='media[]', f=f)
  File "/home/spytec/reddit-twitter-bot/venv/lib/python3.7/site-packages/tweepy/api.py", line 1344, in _pack_image
    raise TweepError('File is too big, must be less than %skb.' % max_size)
tweepy.error.TweepError: File is too big, must be less than 3072kb.
```

Related thread: https://redd.it/aknjma

**Comment by Deadstar106** [comment]
https://github.com/EliteDangerous-Subreddit/reddit-twitter-bot/commit/1ccefa1417dbab6023cb6e7e035f174c0f0ba127

Should do the trick, just a simple if statement, it'll just send the tweet without media otherwise
